travis:
  secure:
    BINSTAR_TOKEN: R85ynWJYfrfi0n6Yw7jYehIUoVZf2ZoPamwxIH/VNl+pJFBxOH+1CnIgG01XC9m9AvneBTKS6yAc9qKr4fXnkvriyDmbHR0MkLRuhf8AsEqOmaFQFptOd5HONRechY1eyLRW9yKxfKgaJBWpRt5vHzDz7LOV1yKXZ09mRkIaoP1ZlHXWCnyER8ROuP+4Ouo7wcR2Kfo4YFsf2geZmp7xoV4u5lNmP/UtJaNGr5vqkXGxFhQtfsHoVc8PRfT+Qm8t0/6ndSVuF0849L4etveQpg4z7473zu9WBh827nvomWHGnP2lyn7wHF3uJJcj/NRT0b2JYESLacMUiz/rK+3gWhcKEsWGf1aqakf8XXoCXZbJGq2e/sz5FdNTXbt2NeIHTXS8BLqWXEKMUX+YdUEU2KUX7nKg3Z40iGFL/m+3TTIag8yAW26t/Oq/9aC5ZcOi6u5HONGAcWLO3u+N+C0YcY8+41mKxe35MxyfBq6LKNvZBMlX+CeF7tKXHJ+ql5DFZ3PCUeZSE/ONZgHnDk5uo2WRVGwCKLkj00IwX6BZK7QZLS3BUUyM573wiAxkRMzmQCP2gmmgfh/K2WhYoP9EYGeYFX17GNs0ifje0dE39zrswWDIoRrvJNiWWNaCBBw5BphWEHCDYiorl2SlBsPwN3TTXygc6ypxLZenIszNR20=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
